### ISSUE TITLE
取关按钮 UI 显示错误

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#1]
一图流。
<img width="407" alt="屏幕快照 2019-12-11 上午2 17 21" src="https://user-images.githubusercontent.com/2507027/70552466-bf916580-1bbc-11ea-94df-bd97488f6261.png">

应与移动端的样式统一。

<img width="253" alt="屏幕快照 2019-12-11 上午2 18 23" src="https://user-images.githubusercontent.com/2507027/70552471-c0c29280-1bbc-11ea-9427-5a00512c713a.png">

**Comment by xiaotiandada** [comment]
谢谢反馈, 我们会修复这个UI显示

**Comment by xiaotiandada** [comment]
> 一图流。
> <img alt="屏幕快照 2019-12-11 上午2 17 21" width="407" src="https://user-images.githubusercontent.com/2507027/70552466-bf916580-1bbc-11ea-94df-bd97488f6261.png">
> 
> 应与移动端的样式统一。
> 
> <img alt="屏幕快照 2019-12-11 上午2 18 23" width="253" src="https://user-images.githubusercontent.com/2507027/70552471-c0c29280-1bbc-11ea-9427-5a00512c713a.png">

谢谢反馈, 我们会修复这个UI显示

**Comment by LittleSound** [comment]
修了，等正式发布之后可以测试。

**Comment by LittleSound** [comment]
已经解决了
