### ISSUE TITLE
【Matataki通知中心】无法准确显示尚未阅读的通知

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#1029]
问题描述：
我一次性收到了22条通知，但是通知页面一次性只能显示下20条消息。当我浏览完第一页的消息，并且使用筛选功能“仅看未读”消息时，筛选结果是空白。并且在通知的小铃铛上显示有2条消息未读。因此除非我点击“加载更多”按钮，否则无法查看那2条未读的消息。
![image](https://user-images.githubusercontent.com/10827774/105796010-d6fdfe80-5fc8-11eb-8faa-ef049e5a67ff.png)
![image](https://user-images.githubusercontent.com/10827774/105796136-22b0a800-5fc9-11eb-9e8b-bfeec5144cd4.png)

**Comment by imbillow** [comment]
https://andoromeda.coding.net/p/smart-signature-backend/d/smart-signature-backend/git/merge/1137

Already resolved
