### ISSUE TITLE
首頁 Logo 顯示失敗

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#1083]
RT
![image](https://user-images.githubusercontent.com/2507027/107905441-8eaf7c00-6f89-11eb-818a-f0a58cdc5db2.png)

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/107930481-02677e00-6fb6-11eb-9a41-554bca093abc.png)

已修复
