### ISSUE TITLE
發布文章時缺省標題的問題

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#1084]
目前發布文章有兩個步驟，如果在第一個不周時未填寫「文章標題」，將會在第二個步驟提示用戶返回重新填寫標題。
用戶第一次使用時，通常流程會被打斷，或者找不到填寫標題的位置，之前進行用戶採訪時，Calvin 也表述了這一憂慮。

解決方案：
1. 在第一個位置缺省標題時就打斷，不讓用戶進入第二個步驟（大部分 blog 系統的作法）。
2. 直接給用戶一個默認的標題，例如「當前發布的時間」（QQ 空間的作法）。

個人認為第二種作法更好，可以最小化對用戶的干擾。

**Comment by guanchao71** [comment]
默认标题采用：发布时间 + “by” +  发布者username
例如 ： 2021.02.03 13:25 by 林可

**Comment by xiaotiandada** [comment]
待测试： https://test.matataki.io

**Comment by LemonNekoGH** [comment]
这个我测试过了 https://test.matataki.io/p/102479

**Comment by lychees** [comment]
LGTM
