### ISSUE TITLE
【2 META】【Matataki QUEST】缩略图

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#1089]
缩略图应该显示基本的任务信息。。。

<img width="230" alt="截屏2021-02-21 上午10 34 16" src="https://user-images.githubusercontent.com/2507027/108613808-5a780780-7430-11eb-9c83-ba3fccc8842a.png">

https://t.me/TwilightParliament/70098

**Comment by billchenchina** [comment]
有点 gg，Quest 是 React 写的。。大概需要针对 `TelegramBot (like TwitterBot)` 这些非浏览器的 UA 加个 server side rendering

**Comment by xiaotiandada** [comment]
需要替换框架重写(这样就不用配置 开箱即用) 可能需要花费一些时间才能解决好
