### ISSUE TITLE
【2 META】【Matataki QUEST】任务领取失败

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#1091]
任务领取失败 0 0。
![image](https://user-images.githubusercontent.com/2507027/108614399-294e0600-7435-11eb-9f91-89f1e6b3dbe9.png)

https://quest.matataki.io/4

**Comment by billchenchina** [comment]
乃用的 Firefox 还是 Chrome...
感觉似乎 cookie 这边有点问题...quq 我这里 Chrome 都登陆不了...

**Comment by xiaotiandada** [comment]
转账功能连带产生的问题

Frank已修复转账功能调整后留下的小bug，这个问题已恢复
