### ISSUE TITLE
一些奇怪的样式问题

### ISSUE THREAD

**Issue by LemonNekoGH** [Matataki-io/Matataki-FE#1096]
点到写文章按钮的::before伪元素也会进入写文章页面
<img width="582" alt="QQ20210224-102149@2x" src="https://user-images.githubusercontent.com/17664845/108940595-9a3c2a80-768e-11eb-9699-08fa6072a39d.png">
屏幕较窄的状态下，写文章按钮激活状态边框大小不匹配的问题
<img width="232" alt="QQ20210224-114457@2x" src="https://user-images.githubusercontent.com/17664845/108944556-eccd1500-7695-11eb-9307-973da173376b.png">

**Comment by xiaotiandada** [comment]
可测试
