### ISSUE TITLE
微信登录功能不可用

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#1118]
此问题频繁出现在桌面端网页中，根据用户反馈在桌面端的Matataki中选择微信登录，在登录页面中会无法加载出来二维码，从而导致无法微信登录。其他端需要工程师自己边测边修复。

**Comment by xiaotiandada** [comment]
1. 取消短链接
2. 修改wx功能 后端初始化代码
3. 修改公众号Api配置

等待版本发布后继续观察问题
