### ISSUE TITLE
文章「展示」和编辑器不一致

### ISSUE THREAD

**Issue by qiwang0** [Matataki-io/Matataki-FE#1219]
在编辑器里使用

markdown语法
`::: hljs-center`

添加样式
`<style>...</style>`

右侧展示都正常

-------------------------
发布之后，却以原内容展示

[例子链接](https://matataki.io/p/8452/?invite=5860&referral=5860)

**Comment by qiwang0** [comment]
以及点击文章中的【图片】，进入对图片的单独展示，那个【旋转】按钮没反应，【1:1】按钮我不懂它在做什么。

**Comment by xiaotiandada** [comment]
> 在编辑器里使用
> 
> markdown语法
> `::: hljs-center`
> 
> 添加样式
> `<style>...</style>`
> 
> 右侧展示都正常
> 
> 发布之后，却以原内容展示
> 
> [例子链接](https://matataki.io/p/8452/?invite=5860&referral=5860)

谢谢反馈

我们会研究并解决以上问题。 style  tag 目前是会被Xss过滤掉的。

**Comment by xiaotiandada** [comment]
> 以及点击文章中的【图片】，进入对图片的单独展示，那个【旋转】按钮没反应，【1:1】按钮我不懂它在做什么。

可能是Bug 我们研究一下 谢谢反馈

**Comment by xiaotiandada** [comment]
> 在编辑器里使用
> 
> markdown语法
> `::: hljs-center`
> 
> 添加样式
> `<style>...</style>`
> 
> 右侧展示都正常
> 
> 发布之后，却以原内容展示
> 
> [例子链接](https://matataki.io/p/8452/?invite=5860&referral=5860)

已修复 等待下次发布版本
