### ISSUE TITLE
在英文状态下的「写文章」按钮的边框依然会和按钮本体不匹配

### ISSUE THREAD

**Issue by LemonNekoGH** [Matataki-io/Matataki-FE#1235]
<img width="218" alt="截屏2021-05-08 12 18 52" src="https://user-images.githubusercontent.com/17664845/117526444-cdd4f280-aff7-11eb-8918-5e03d04573ff.png">

**Comment by xiaotiandada** [comment]
https://github.com/Matataki-io/Matataki-FE/pull/1260
