### ISSUE TITLE
【DAO工具】网站已经无法使用

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#1246]
**正常状态描述**
如果功能正常，应当在 MAtataki DAO中出现对应每一种Fan票都有个独立的治理入口，点击进入任何Fan票的治理页面，用户都可以发起提案，并且可以设置对提案进行二次方投票。
**解决方案**
需要重新检查问题出现的原因，然后将其功能可用
![image](https://user-images.githubusercontent.com/10827774/117747470-d10eef00-b240-11eb-9c5e-6f3f0c89e641.png)

**Comment by xiaotiandada** [comment]
已处理
