### ISSUE TITLE
【Matataki】进入有权限的文章后会连续弹出3次提示

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#1251]
**问题描述**
当用户处于未登录或是权限不足的状态，进入设定需要持币/支付查看的文章页面时，界面上会连续弹出3次红色的权限不足提示警告。然而界面上本身时做了又对应的权限状态 UI 的，无需向用户进行红色警告式提醒。
**解决方案**
去除上述状态下全部的“权限不足”提醒
**问题图片**
![image](https://user-images.githubusercontent.com/10827774/117913080-46e38b00-b313-11eb-90d2-57f4faa947f5.png)

**Comment by xiaotiandada** [comment]
#1264
