### ISSUE TITLE
优化 onboarding 流程。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#1261]
以 [这篇文章](https://www.matataki.io/p/5093
) 举例，希望新用户点解锁触发登录账号之后，可立刻跳转到支付界面，可能存在其他地方也需要做类似的调整。

<img width="874" alt="截屏2021-05-26 下午4 24 14" src="https://user-images.githubusercontent.com/2507027/119627472-d1150e80-be3e-11eb-8d8d-fc526e1e2111.png">

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/119823694-aeaaf000-bf27-11eb-9db1-07515c43ff09.png)

![image](https://user-images.githubusercontent.com/24250627/119823859-dd28cb00-bf27-11eb-9a78-0b55383811cd.png)


待测试    点击 一件解锁未登录用户会先登录(邮箱登录)后会自动显示创建订单的Modal框

> ps: 如果是其他登录方式新开了窗口然后再返回的方式可能不会自动打开Modal框，需要再点击一下。为了保证最小影响暂时使用的是 session 存储点击方式，后续可以根据需求修改存储方式

#1264

**Comment by xiaotiandada** [comment]
测试后还有 bug
如果满足条件但是 未登录点击解锁，登录后也会弹出订单框

**Comment by xiaotiandada** [comment]
> 测试后还有 bug
> 
> 1. 如果满足条件但是 未登录点击解锁，登录后也会弹出订单框
> 2. 样式问题 目前打包不支持 `box-shadow: 0 1px 2px 0 rgb(0 0 0 / 5%);` 这种格式 会丢掉样式

已处理 等待下一次发布
