### ISSUE TITLE
有链接打开，会处在非登入状态

### ISSUE THREAD

**Issue by zjiekai** [Matataki-io/Matataki-FE#1262]
比如 https://matataki.io/p/5040 ，我打开后会处在非登入状态。

但是打开 https://www.matataki.io/p/5093 ，就是正常的。

我的用户页面 https://www.matataki.io/user/2600

**Comment by lychees** [comment]
这个好像是 github 的 cookie 掉了，重新登录一下试试？

**Comment by zjiekai** [comment]
我这次是输入邮箱密码来登入的

**Comment by zjiekai** [comment]
好像在显示为非登入的页面，在登入一次（我是用的邮箱 / 密码），还是不影响使用的

**Comment by xiaotiandada** [comment]
已处理域名重定向 谢谢反馈 ❤️
