### ISSUE TITLE
希望可以在相关位置增加 txid 的超链接。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#162]
- [x] Fan 票流水
- [x] Bot 反馈

<img width="718" alt="屏幕快照 2020-01-18 下午7 04 41" src="https://user-images.githubusercontent.com/2507027/72662717-6b806900-3a25-11ea-84a5-40adac16df9d.png">

<img width="285" alt="屏幕快照 2020-01-18 下午7 05 27" src="https://user-images.githubusercontent.com/2507027/72662734-94086300-3a25-11ea-8f2e-32f460535f1a.png">

**Comment by LittleSound** [comment]
https://github.com/Matataki-io/Matataki-FE/pull/267
https://github.com/Matataki-io/Matataki-Mobile-FE/pull/272
