### ISSUE TITLE
分享 token 页面链接时，未显示 Token 信息。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#164]
e.g.: https://twitter.com/MinakoOikawa/status/1218786490571882497

<img width="602" alt="屏幕快照 2020-01-19 下午2 45 30" src="https://user-images.githubusercontent.com/2507027/72676284-6d503800-3aca-11ea-85c5-34b167b614e4.png">

用户页面问题类似。
https://www.matataki.io/user/1508

**Comment by LittleSound** [comment]
已解决，Pr：
https://github.com/Matataki-io/Matataki-FE/pull/181
https://github.com/Matataki-io/Matataki-FE/pull/182

**Comment by LittleSound** [comment]
个人主页也添加了该功能：https://github.com/Matataki-io/Matataki-FE/pull/192

**Comment by lychees** [comment]
LGTM.
