### ISSUE TITLE
付费内容可通过 ipfs 保护模式阅读的 bug

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#2]
https://www.matataki.io/ipfs/QmQUkeoygzHBuWM9SvP7Bk6BUyqj4vhM2cJVFEsShisvBx?c=94a0df1f

以这个为例，隔壁移动端工作正常。

**Comment by xiaotiandada** [comment]
> https://www.matataki.io/ipfs/QmQUkeoygzHBuWM9SvP7Bk6BUyqj4vhM2cJVFEsShisvBx?c=94a0df1f
> 
> 以这个为例，隔壁移动端工作正常。

谢谢反馈，我们会修复 👍

**Comment by guanchao71** [comment]
https://www.matataki.io/p/1400
举例这篇文章，没有购买的情况下就可以看到ipfs地址啦
