### ISSUE TITLE
改善Matataki

### ISSUE THREAD

**Issue by xiaotiandada** [Matataki-io/Matataki-FE#334]
1. 重新设计首页样式和文案
2. 简化和合并菜单内容
3. 删除分享大厅、双向索引、积分领取的功能 -- 小田 pc端已处理完成
4. 优化文内加密功能，功能越简单直接越好
5. 结合评论功能，嵌入可选打赏文章Fan票的功能，去除积分消耗
6. 以侧边栏的形式插入Fan票钱包功能，可以在任意页面唤出，支持查余额，转账、跳转到FanToken网站查看明细
7. 完善强提醒功能
8. 优化文章编辑器的编辑和发布流程
9. 和FanToken系统解耦
10. 优化访问打开体验
11. 稳定基本面功能的稳定性
12. 更换域名
13. 采用自适应前端统一多端体验  -- 小田 正在做
14. 增加Hash历史查询功能
15. 针对登录用户优先展示推荐内容：关注对象的更新 和 推荐内容
16. 重新开发文章的标签系统

**Comment by shellteo** [comment]
17. 第一个打开出现移动端页面
![image](https://user-images.githubusercontent.com/16064604/81262678-d6a38900-9070-11ea-9cc9-a4d1b9196580.png)

**Comment by shellteo** [comment]
18. ElasticSearch 导入新文章/新用户报错

**Comment by shellteo** [comment]
19. 各种no content / loading的ui优化

**Comment by xiaotiandada** [comment]
双向索引
包含:
发布选择, 文章展示

状态:
正在做

**Comment by xiaotiandada** [comment]
首页界面样式修改

状态: 正在做

**Comment by xiaotiandada** [comment]
发文移除积分设置, 界面细节调整

**Comment by xiaotiandada** [comment]
2020-5-9

1. 通知页面修改

正在做
