### ISSUE TITLE
文章编辑器页面调整

### ISSUE THREAD

**Issue by xiaotiandada** [Matataki-io/Matataki-FE#351]
按照lanhu原型调整

**Comment by guanchao71** [comment]
将所有的设置内容转移到独立的 设置 弹窗页面中
新增加预览链接功能，可以让任何人查看草稿箱文章的预览效果
新增加默认权限选项：所有人可看 & 仅自己可编辑
将删除草稿和转移草稿入口也转移到 设置 弹窗页中

点击立即发布按钮会弹出简化版的 设置 弹窗页，相比原版减少了：删除草稿和转移草稿的功能。

**Comment by xiaotiandada** [comment]
预览功能

1. 要做哪些功能(谁能看 还是只能自己看) 
2. 需要展示哪些信息
3. 待补充....

**Comment by guanchao71** [comment]
> 预览功能
> 
> 1. 要做哪些功能(谁能看 还是只能自己看)
> 2. 需要展示哪些信息
> 3. 待补充....

A1：任何知道链接的人都可以看
A2：需要展示：标题、创作者、正文内容
