### ISSUE TITLE
[Bug] 小屏幕下发布文章按钮会找不到

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#397]
<img width="665" alt="屏幕快照 2020-05-21 上午8 47 52" src="https://user-images.githubusercontent.com/2507027/82560701-f0989d80-9b3f-11ea-8bbe-ba4a09998883.png">
<img width="663" alt="屏幕快照 2020-05-21 上午8 47 57" src="https://user-images.githubusercontent.com/2507027/82560702-f0989d80-9b3f-11ea-9856-4b8ab1401e68.png">

一图流。
点击原创声明后，底部包括发布文章按钮的 dom 元素会被遮盖，滚动无效，需要缩小屏幕 “ctrl + -” 才能出现。

**Comment by xiaotiandada** [comment]
> <img alt="屏幕快照 2020-05-21 上午8 47 52" width="665" src="https://user-images.githubusercontent.com/2507027/82560701-f0989d80-9b3f-11ea-8bbe-ba4a09998883.png">
> 
> <img alt="屏幕快照 2020-05-21 上午8 47 57" width="663" src="https://user-images.githubusercontent.com/2507027/82560702-f0989d80-9b3f-11ea-9856-4b8ab1401e68.png">
> 
> 一图流。
> 点击原创声明后，底部包括发布文章按钮的 dom 元素会被遮盖，滚动无效，需要缩小屏幕 “ctrl + -” 才能出现。

感谢反馈 这个bug已经修复 下个版本将会发出

**Comment by xiaotiandada** [comment]
已修复
