### ISSUE TITLE
导入igaojin.me的文章排版有问题.

### ISSUE THREAD

**Issue by jin10086** [Matataki-io/Matataki-FE#43]
比如可以测试 这一篇https://igaojin.me/2019/11/30/%E7%A8%8B%E5%BA%8F%E5%91%98%E6%89%BE%E5%AF%B9%E8%B1%A1%E8%81%9A%E5%90%88%E5%B9%B3%E5%8F%B0-xunta-today/

还有 能不能有个api，只要我生成token后,只要输入某个网址后，自动导入文章，不需要我再点确认了

**Comment by xiaotiandada** [comment]
谢谢反馈, 后面我们会优化这个问题

**Comment by xiaotiandada** [comment]
> 比如可以测试 这一篇https://igaojin.me/2019/11/30/%E7%A8%8B%E5%BA%8F%E5%91%98%E6%89%BE%E5%AF%B9%E8%B1%A1%E8%81%9A%E5%90%88%E5%B9%B3%E5%8F%B0-xunta-today/
> 
> 还有 能不能有个api，只要我生成token后,只要输入某个网址后，自动导入文章，不需要我再点确认了

谢谢反馈, 后面我们会优化这个问题 👍

**Comment by lychees** [comment]
Deprecated.
