### ISSUE TITLE
【悬赏】【2000 DAO】推特登陆与绑定

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#466]
这个功能感觉卡的有点久。。。

**Comment by Kumo-YZX** [comment]
under construction yet now...
![image](https://user-images.githubusercontent.com/16816538/85222739-420ea380-b3f0-11ea-881c-1081f45da9ca.png)

**Comment by Kumo-YZX** [comment]
> under construction yet now...
> ![image](https://user-images.githubusercontent.com/16816538/85222739-420ea380-b3f0-11ea-881c-1081f45da9ca.png)

failed to do this

**Comment by Kumo-YZX** [comment]
> under construction yet now...
> ![image](https://user-images.githubusercontent.com/16816538/85222739-420ea380-b3f0-11ea-881c-1081f45da9ca.png)

There must be someone who can do better than me.

**Comment by lychees** [comment]
LGTM. Well Done.
https://rinkeby.etherscan.io/tx/0x3148497586987215bb1e48586c97fb093792e631a89c69c73afd1a2bfdbbd84c

**Comment by sillycat2** [comment]
还是没法绑定啊，，

**Comment by sillycat2** [comment]
登录倒是可以用，可是显示登录成功，然后进站里还显示没登录！咋滴了？？？
