### ISSUE TITLE
Add "Sign In" with AlphaWallet

### ISSUE THREAD

**Issue by zhangzhongnan928** [Matataki-io/Matataki-FE#526]
![IMG_3546](https://user-images.githubusercontent.com/33795543/85080895-b9381200-b20d-11ea-8d6f-d275945ecf4e.PNG)

Hi, is that possible to add "Sign In" with AlphaWallet?

How to Identify AlphaWallet Provider
https://github.com/AlphaWallet/AlphaWallet-web3-provider

AlphaWallet iOS & Android:
https://github.com/AlphaWallet/alpha-wallet-ios
https://github.com/AlphaWallet/alpha-wallet-android

Currently, if I click "Log in with MetaMask in AlphaWallet browser, it shows an error as below,

![IMG_3542](https://user-images.githubusercontent.com/33795543/85080567-e0421400-b20c-11ea-9e1e-5e5c4fb02fd6.PNG)

**Comment by guanchao71** [comment]
I think you want to express: login with AlphaWallet by Ethereum ？

**Comment by zhangzhongnan928** [comment]
> I think you want to express: login with AlphaWallet by Ethereum ？

Yes.

**Comment by lychees** [comment]
deprecated at this moment.
