### ISSUE TITLE
昵称框不允许「日语」出现

### ISSUE THREAD

**Issue by nekomeowww** [Matataki-io/Matataki-FE#537]
应该是 Regex 出现的问题
或者是其他的语言检测，或者说的确是只能允许所谓的「0-9，中文，英文，符号」出现

**Comment by xiaotiandada** [comment]
> 应该是 Regex 出现的问题
> 或者是其他的语言检测，或者说的确是只能允许所谓的「0-9，中文，英文，符号」出现

感谢体验反馈

规则基本上都才对了233~, 这个 issues 已经反馈给了产品. 

等待产品经理的考虑结果!

谢谢🙏

**Comment by nekomeowww** [comment]
好的，谢谢你的审阅

**Comment by nekomeowww** [comment]
后端也修复了。
