### ISSUE TITLE
文章阅读页面登录后跳转至404

### ISSUE THREAD

**Issue by liyishuai** [Matataki-io/Matataki-FE#54]
## 运行环境
- macOS 10.15.1
- Safari 13.0.3
## 复现过程
1. 访问文章https://www.matataki.io/p/1194
2. GitHub账号登录
3. 跳转至https://www.matataki.io/p
## 屏幕实录
https://lys.keybase.pub/matataki.mov

**Comment by liyishuai** [comment]
测试员：[lys](https://www.matataki.io/user/947)

**Comment by guanchao71** [comment]
> 测试员：[lys](https://www.matataki.io/user/947)

![image](https://user-images.githubusercontent.com/10827774/71151565-02170a00-226f-11ea-9276-2b036c39fb76.png)

贡献Issues奖励DAO（数量随机的）

**Comment by xiaotiandada** [comment]
> ## 运行环境
> * macOS 10.15.1
> * Safari 13.0.3
> 
> ## 复现过程
> 1. 访问文章https://www.matataki.io/p/1194
> 2. GitHub账号登录
> 3. 跳转至https://www.matataki.io/p
> 
> ## 屏幕实录
> https://lys.keybase.pub/matataki.mov

谢谢反馈, 我们会尽快修复

**Comment by xiaotiandada** [comment]
> ## 运行环境
> * macOS 10.15.1
> * Safari 13.0.3
> 
> ## 复现过程
> 1. 访问文章https://www.matataki.io/p/1194
> 2. GitHub账号登录
> 3. 跳转至https://www.matataki.io/p
> 
> ## 屏幕实录
> https://lys.keybase.pub/matataki.mov

感谢您的使用并反馈bug, 我们已经修复这个问题并且已经更新

地址: https://www.matataki.io

谢谢您的支持 🎉🎉🎉
