### ISSUE TITLE
🎫 生产环境无法交易 Fan票

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#563]
一图流。

<img width="1367" alt="截屏2020-06-24 下午5 49 12" src="https://user-images.githubusercontent.com/2507027/85641354-2e0eb000-b643-11ea-8aec-67d37fb2e025.png">

试了其它 Fan票 也产生了同样的错误。

**Comment by frankwei98** [comment]
我这边可以，怀疑是你的网络问题
![image](https://user-images.githubusercontent.com/3261732/85679770-4b538500-b6fc-11ea-8052-58bb06660a2a.png)

**Comment by lychees** [comment]
上面的这笔交易我并没有在
https://matataki.io/token/22?tab=1
找到，

但似乎链上是有记录的，
![image](https://user-images.githubusercontent.com/2507027/85689768-c6c71f00-b687-11ea-8545-72c4ba1df5dc.png)

我已经搞乱了。

**Comment by lychees** [comment]
转帐（以及打赏）交易是正常的。
问题看起来出现在与 uniswap 通信上。

**Comment by shellteo** [comment]
token -> cny ✅ already fixed
token -> token ✅ already fixed

**Comment by lychees** [comment]
Problem solved.
