### ISSUE TITLE
分享结果的不完美抓取。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#569]
<img width="447" alt="截屏2020-06-25 上午5 36 26" src="https://user-images.githubusercontent.com/2507027/85721021-d2c1d980-b6a5-11ea-9a08-82454bfc1421.png">

显然不应该显示网页地址。。
而应该显示正文的一部分内容。。。

[4.3.0 版本](https://matataki.io/p/4390) 更新之前并没有这些问题。。。

**Comment by xiaotiandada** [comment]
谢谢反馈 我们会尽快处理

**Comment by xiaotiandada** [comment]
> <img alt="截屏2020-06-25 上午5 36 26" width="447" src="https://user-images.githubusercontent.com/2507027/85721021-d2c1d980-b6a5-11ea-9a08-82454bfc1421.png">
> 
> 显然不应该显示网页地址。。
> 而应该显示正文的一部分内容。。。
> 
> [4.3.0 版本](https://matataki.io/p/4390) 更新之前并没有这些问题。。。

应该是网络的原因, 某些请求还没发送完毕 客户端就已经发送分享了!

**Comment by xiaotiandada** [comment]
#600
