### ISSUE TITLE
登录跳转和表单登录的无法刷新 session 问题

### ISSUE THREAD

**Issue by nekomeowww** [Matataki-io/Matataki-FE#570]
## 1
这边先用了表单 email + passwd 登录
然后没有反应，Ctrl + R 之后还是没有反应
然后继续尝试用表单 email + passwd 登录，还是没有反应
## 2
然后点击了 GitHub 登陆，结果 callback url 的时候告诉我 404
跳转回主页之后能看到自己的帐号了，现在以为可以访问了，然后开了新的 tab 访问文章
发现登陆又没了
## 3
又继续用 email + passwd 表单登陆
没有反应
继续自动填写一次，可以了，然后现在 cookies 才正常

## 建议
建议检查 GitHub callback url 的问题
还有表单提交的 session update 问题

**Comment by xiaotiandada** [comment]
感谢您的的反馈

邮箱登录我们这边已经处理了, 有空您再试一下 随时欢迎您的体验反馈

github callback url这边我们也会尽快处理的

谢谢

**Comment by nekomeowww** [comment]
好的，我这边也会看一下代码
