### ISSUE TITLE
打賞選項裡，沒有 CNY。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#573]
<img width="467" alt="截屏2020-06-24 上午12 43 15" src="https://user-images.githubusercontent.com/2507027/85893366-9bd3ec80-b7a7-11ea-999e-f29272599476.png">

**Comment by xiaotiandada** [comment]
因为功能设计的原因 已经反馈给产品经理了 

谢谢您的反馈

**Comment by guanchao71** [comment]
这个需求已经得到认可，正在开发中。感谢反馈
