### ISSUE TITLE
Firefox 上出现搜索框遮挡登录按钮问题

### ISSUE THREAD

**Issue by ayalhw** [Matataki-io/Matataki-FE#576]
系统及浏览器环境79.0a1.20200626.22-1
- Mozilla Firefox 79.0a1 20200626094540 （具体是来自 Arch CN 源的79.0a1.20200626.22-1, 链接：https://repo.archlinuxcn.org/x86_64/firefox-nightly-zh-cn-79.0a1.20200626.22-1-x86_64.pkg.tar.zst）
- Arch Linux

症状：
![图片](https://user-images.githubusercontent.com/43064781/85922204-0a9e6c00-b8b4-11ea-8d22-051fb782b2ee.png)
如图，输入框宽度过大遮挡了登录按钮，使得登录按钮无法点击
在日常的配置和火狐安全模式下+新的profile下均进行了测试
其他网站未发现此问题，Chromium 下无此问题

Edit：
- 在火狐稳定版复现 77.0.1
- 在火狐开发者版复现 78.0b9
- 在火狐 ESR 版复现 68.9.0

**Comment by ayalhw** [comment]
我现在有点怀疑是不是我的系统问题了……怎么在 ESR 版火狐都能复现……

**Comment by xiaotiandada** [comment]
> 我现在有点怀疑是不是我的系统问题了……怎么在 ESR 版火狐都能复现……

我这边的 mac firefox developer Edition v78.0b5 (64-bit) 暂未发现该问题 🤣
