### ISSUE TITLE
Github 登陆后 404。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#579]
随后文章页面依然登陆失败，
但跳转到首页可以执行一次 Logout，
再次使用 Github 登录后一切正常。
疑似是 token 失效。。

**Comment by xiaotiandada** [comment]
> 随后文章页面依然登陆失败，
> 但跳转到首页可以执行一次 Logout，
> 再次使用 Github 登录后一切正常。
> 疑似是 token 失效。。

谢谢反馈

应该是 callback 后地址的问题, 导致 url 没有匹配的页面, 已修复 下一个版本将会发出

**Comment by lychees** [comment]
@xiaotiandada 相关修复的 pr attach 一下。

**Comment by xiaotiandada** [comment]
#594
