### ISSUE TITLE
添加流动金时显示价格波动

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#584]
<img width="672" alt="截屏2020-06-29 下午9 50 01" src="https://user-images.githubusercontent.com/2507027/86084778-8c2c0080-ba52-11ea-822f-b60e9b91c707.png">

stake 怎么会产生价格波动呢。。。
建议删除。

**Comment by shellteo** [comment]
fixed, https://github.com/Matataki-io/Matataki-FE/pull/586
