### ISSUE TITLE
移动端的调整建议

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#599]
采访了几个用户（中国大妈）。
纷纷表示玩不懂。
https://www.matataki.io/token/22

1. 大妈用户只会使用微信浏览器。
2. 如果检测到是微信浏览器，如果没有登录且在 token 的页面，直接提示是否用微信登录？
3. 快捷购买的位置应该调整到更前面。（至少在各种转账流水记录之前，因为这部分用户上来就是要交易）

这部分用户的体验自然是非常重要的。。。
原因当然不仅仅是它们会比较闲（both money && time），
更重要的是，family member 应该成为 initial liquidity offer 的重要组成部分。
甚至未来的子女抚养和老人赡养都可以通过买 token 来完成
（上学的时候，家长买子女的 token，子女卖出自己的 token 换取生活费、学费，
长大后，家长卖子女的 token，来作为自己养育孩子的合理回报，一口气解决世纪难题。Toward brave new world...
Bingo！！）

**Comment by guanchao71** [comment]
你提到的几个需求是合理的，我们将会尽快去解决第二点和第三点建议。
