### ISSUE TITLE
Github登陆后，自动生成的Nickname可能会造成修改user information时报错

### ISSUE THREAD

**Issue by zhangzhongnan928** [Matataki-io/Matataki-FE#601]
Matataki系统设定的Nickname格式是不允许有空格的，但是如果Matataki账号是由github登陆创建的（没有测试其他登录方式，应该也会有类似问题），是有可能生成带有空格的Nickname。

这时如果用户去修改user information，会因为Nickname内的空格导致修改失败。

<img width="1250" alt="Screen Shot 2020-07-02 at 10 30 45 am" src="https://user-images.githubusercontent.com/33795543/86303632-c4e4f900-bc4f-11ea-96b5-13c9c65e3b74.png">

而且由于错误信息不清楚，用户自己很难发现是需要去除Nickname内的空格

**Comment by lychees** [comment]
收到，感谢报告！

**Comment by guanchao71** [comment]
此问题 在 #966 #967  中已经开始着手改进，此Issue关闭。
