### ISSUE TITLE
加入登录方式找回功能

### ISSUE THREAD

**Issue by misaka00251** [Matataki-io/Matataki-FE#636]
~~不知道怎么说好~~

就是如果忘记登录方式又没有绑定邮箱~~的罕见情况~~，一个一个通过第三方登录去试的话可能是比较麻烦的事情，所以希望能增加一个类似的功能 :D

**Comment by shellteo** [comment]
这种情况的话很难去找回了，因为你那边不能提供有效信息，我们系统也找不回你的账号，只能你一个个去试。
而且为了用户注册使用，我们平台是没有强制要求用户绑定手机/邮箱的。
