### ISSUE TITLE
热门内容长期不更新，希望可以降低 priority。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#76]
<img width="608" alt="屏幕快照 2019-12-25 下午4 13 42" src="https://user-images.githubusercontent.com/2507027/71450516-90890100-2731-11ea-8a08-5b20909e14ff.png">

不如把顺序调整成。。。我的关注 | 最新 | 热门。。。？

**Comment by xiaotiandada** [comment]
> <img alt="屏幕快照 2019-12-25 下午4 13 42" width="608" src="https://user-images.githubusercontent.com/2507027/71450516-90890100-2731-11ea-8a08-5b20909e14ff.png">
> 
> 不如把顺序调整成。。。我的关注 | 最新 | 热门。。。？

那样会不会一打开就是 无关注 , 最新文章: xx文章 lj文章 sq文章 xx文章

**Comment by guanchao71** [comment]
> <img alt="屏幕快照 2019-12-25 下午4 13 42" width="608" src="https://user-images.githubusercontent.com/2507027/71450516-90890100-2731-11ea-8a08-5b20909e14ff.png">
> 
> 不如把顺序调整成。。。我的关注 | 最新 | 热门。。。？

这种解决方案治标不治本，我们需要调整“热门”列表的内容展示规则。

**Comment by lychees** [comment]
<img width="879" alt="屏幕快照 2019-12-30 下午10 08 40" src="https://user-images.githubusercontent.com/2507027/71608739-582e5c00-2b51-11ea-8f3c-8de90ec1367a.png">

先把默认改成最新吧。。。

**Comment by xiaotiandada** [comment]
> <img alt="屏幕快照 2019-12-30 下午10 08 40" width="879" src="https://user-images.githubusercontent.com/2507027/71608739-582e5c00-2b51-11ea-8f3c-8de90ec1367a.png">
> 
> 先把默认改成最新吧。。。

等待新版上线 排序将替换位置🎉

**Comment by xiaotiandada** [comment]
已更新, 体验地址: https://www.matataki.io/article
