### ISSUE TITLE
用户页面的转账应包含 cny。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#831]
https://matataki.io/user/526

<img width="347" alt="截屏2020-08-17 上午3 28 49" src="https://user-images.githubusercontent.com/2507027/90386687-c751b580-e039-11ea-84b8-5050905b1d81.png">

**Comment by shellteo** [comment]
因为功能设计的原因 已经反馈给产品经理了

谢谢您的反馈

**Comment by guanchao71** [comment]
产品经理表示已经在开发了

**Comment by guanchao71** [comment]
这个功能已经在4.7.0版本中推出上线
![image](https://user-images.githubusercontent.com/10827774/91973063-2d368080-ed4e-11ea-90c3-f6fe301afcd0.png)
