### ISSUE TITLE
直通车支付时提示没有流动性

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#870]
Which 其实有。。
https://matataki.io/p/5238

我支付后成功了，需要有人再来 double check 一下

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/91972882-e6e12180-ed4d-11ea-9abe-4e31f1993f91.png)
这个问题我测试后没有复现，在直通车中的确是没有流动性提供，选择选项1通过交易所快捷购买是有流动性的。
