### ISSUE TITLE
解锁编辑权限 Typo

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#871]
![截屏2020-09-02 下午12 41 39](https://user-images.githubusercontent.com/2507027/92029044-ce571400-ed19-11ea-9d27-63279a8e98fb.png)

一图流。

**Comment by LittleSound** [comment]
这不是一个错误，解锁阅读权限是解锁编辑权限的条件。

**Comment by Garfield550** [comment]
![image](https://user-images.githubusercontent.com/3471836/92229963-e034e480-eedc-11ea-9a59-d09430ef3096.png)

换成这种提示呢？（我审查元素的
