### ISSUE TITLE
反复删除流动金

### ISSUE THREAD

**Issue by liyishuai** [Matataki-io/Matataki-FE#873]
## 运行环境
- macOS 10.13.6
- Google Chrome 85.0.4183.83
## 问题描述
点击“删除流动金Token”后，起先无反应；重复点击同一按钮多次后，弹出即将刷新页面信息，并已完成多次删除流动金操作。
## 预期
点击按钮后，刷新页面前，不可再次点击此按钮。

测试员：[lys](https://www.matataki.io/user/947)

**Comment by lychees** [comment]
deprecated.
