### ISSUE TITLE
修复主网 Twitter 登陆 && 绑定的 bug。

### ISSUE THREAD

**Issue by lychees** [Matataki-io/Matataki-FE#886]
测试网是好的，twitter 相关的代码都没改过，
是下面的 cdn 把那个登录页面映射到一个不存在的 url 上。

![image](https://user-images.githubusercontent.com/2507027/98385228-b6896c80-2089-11eb-8f4e-04f3ecfadea5.png)

**Comment by sillycat2** [comment]
哎呀，终于来了，感谢感谢。

**Comment by lychees** [comment]
> 哎呀，终于来了，感谢感谢。
啥情况呀。。。兄弟。。

**Comment by sillycat2** [comment]
现在好了
