### ISSUE TITLE
[UI优化] 优化一下 bscMintWithPermit 页面的界面UI

### ISSUE THREAD

**Issue by frankwei98** [Matataki-io/Matataki-FE#897]
现在 `/token/bscMintWithPermit` 的界面比较乱 [代码在这儿](https://github.com/Matataki-io/Matataki-FE/blob/testing/pages/token/bscMintWithPermit.vue)

需要懂CSS懂UI的老铁完善一下布局和交互。

发送交易的功能应该是没问题的，可以不用管。只需要管这个页面的 UI 和交互逻辑即可。

![image](https://user-images.githubusercontent.com/3261732/99495187-3928fa80-29ad-11eb-9100-bff26885d5a4.png)

**Comment by xiaotiandada** [comment]
已提交 #903
