### ISSUE TITLE
【5 META】在添加文内加密内容后，会错误将加密部分界面显示2次

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#963]
RT [详细信息待补充]

**Comment by xiaotiandada** [comment]
#999

**Comment by xiaotiandada** [comment]
https://test.matataki.io/p/102323

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/103858382-2ef4c400-50f3-11eb-92c6-bdc9639fc641.png)

**Comment by lychees** [comment]
Can we close this issue now?
