### ISSUE TITLE
【20 META】为新注册的用户自动设置随机昵称

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#966]
## 问题
在过去的版本中，Matataki会将新用户的注册渠道作为默认昵称，而往往这些昵称在长度或是字符上并不符合Matataki的昵称规范，因此Matataki采用了 “在生成默认昵称的时候可以违反昵称规范”这样的规则来处理，但是当用户在修改个人信息并保存的时候，会被系统进行自动检测，页面中的各种设置是否 合法。这时候明明用户没有调整自己昵称，但是在保存其他修改的时候就被被提示“昵称有问题”，这样会对用户造成非常大的困惑。根本原因就是在于我们帮用户设定了一个“虚假”的昵称，但是在用户看来这就是他们的真实昵称。

## 解决方案

- [x] 1. 无论使用何种渠道首次登陆Matataki的用户都会被分配一个“真正”的随机昵称
- [x] 2. 该昵称的格式为 “USER”+“随机字符” 形式，来标明这是个系统自动分配的昵称
- [x] 3. #967 开放昵称中对字符的限制，以适应更多的用户需求

**Comment by xiaotiandada** [comment]
1、2 已完成开发 可测试

**Comment by xiaotiandada** [comment]
1. wechat https://test.matataki.io/user/1391
2. github https://test.matataki.io/user/1390
3. telegram 无法测试
4. twitter https://test.matataki.io/user/1392
5. google https://test.matataki.io/user/1393
6. email https://test.matataki.io/user/1394
7. eth ✅

**Comment by xiaotiandada** [comment]
1. wechat https://test.matataki.io/user/1391
2. github https://test.matataki.io/user/1390
3. telegram 无法测试
4. twitter https://test.matataki.io/user/1392
5. google https://test.matataki.io/user/1393
6. email https://test.matataki.io/user/1394
7. eth https://test.matataki.io/user/1389

**Comment by guanchao71** [comment]
META奖励已发放 ：https://rinkeby.etherscan.io/tx/0x201c7d20ef00c9d96fad506f6f3228f8c519218e87fb83375901e9782e66ab16
Matataki感谢您的支持~
