### ISSUE TITLE
【15 META】在用户昵称设置中增加对常用字符的支持

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#967]
- [x] @ 
- [x] 空格 
- [x] \
- [x]  /
- [x] [
- [x] ]
- [ ] 还有其它的常用字符由开发来补充

#601 中有提到此问题造成的影响

**Comment by xiaotiandada** [comment]
新增 . 

xxx@xxxx.com

**Comment by xiaotiandada** [comment]
#993 可测试

**Comment by guanchao71** [comment]
https://rinkeby.etherscan.io/tx/0xf8b0b023cc4fd5121dad9fd3635e79284de9fd3a564d4868558af3777bb99bd5
奖励已经发放，感谢对Matataki的支持
