### ISSUE TITLE
【1 META】为空投Dapp的首页Login 入口实装功能

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#968]
- [x] Login功能
- [x] Send功能
- [x] Redeem功能

![image](https://user-images.githubusercontent.com/10827774/103301845-36ee9d00-4a3d-11eb-8088-a9337b9bcc83.png)

**Comment by xiaotiandada** [comment]
https://github.com/NaoMikuOshi/Matataki-Token-AirDropper/pull/39
