### ISSUE TITLE
【2 META】【Fan票交换事务所】搜索Fan票的时候增加实时筛查特性

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#970]
当我在搜索Fan票的时候，希望可以在我输入的同时就对输入字符进行搜索并筛选出备选项，而无需等待我去按下回车按钮。因为在手机上这并非是一个常见的操作。
![image](https://user-images.githubusercontent.com/10827774/103394438-6ef00000-4b63-11eb-827b-ac13e5c0ab6c.png)

**Comment by xiaotiandada** [comment]
#1002 可以测试

**Comment by guanchao71** [comment]
META奖励已发放 ： 0xb7131dc86f0592e15ee416b3714b26819c80c526b1032c13d2adf832332d34da
Matataki感谢您的贡献！
