### ISSUE TITLE
【0.5 META】【Fan票交换事务所】优化搜索界面中打开Fan票主页的入口，增强表意效果

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#971]
目前的打开主页功能按钮采用的是类似于“分享”图标的样式，没有使用经验的用户完全无法从图标上明白该按钮有什么功能。因此我希望做出如下调整：

- [x] 1. 重新设计图标，能够代表Fan票的主页
- [x] 2. 增加鼠标指向提示“查看主页”

![image](https://user-images.githubusercontent.com/10827774/103394457-aeb6e780-4b63-11eb-808e-6a7a94efbb2b.png)

---

设计稿
![image](https://user-images.githubusercontent.com/10827774/103758097-ab809780-504c-11eb-8c8b-33de0ecaff54.png)

**Comment by xiaotiandada** [comment]
#1004 可测试

**Comment by guanchao71** [comment]
META奖励已发放 ：0x1c2ef05d0690ceacb1e7c58484425b2ef633d26ac24697d4cccf730abdc12439
感谢您的开发~
