### ISSUE TITLE
【10 META】【Fan票信息可视化】【设计中】增加对 Fan票跨链后的多链信息展示

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#972]
自从增加了BSC跨链导入导出功能后，有许多场景的业务逻辑就不能通过当前的信息架构来充分展示相关信息了。并且由于收到了

**Comment by ChaunceyHook** [comment]
![Fan票详情页_转账](https://user-images.githubusercontent.com/51438318/103858732-d4a83300-50f3-11eb-91f0-bc5c58106f17.png)
