### ISSUE TITLE
【0.5 META】文章发布后端额Description部分没有空格

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#981]
## 问题描述
该文章 https://matataki.io/p/6348 发布后，在发现页面的 文章列表中表现为 英文字符之间紧密粘结，丢失了基本的空格信息。
猜测可能是由于在存储文章的时候，对所有空格都进行了去除导致的结果，并不仅针对英文，只是在英文中表现尤为明显。
![image](https://user-images.githubusercontent.com/10827774/103601717-35ddd400-4f45-11eb-8041-e51f4ded0743.png)

## 修改方案
调整文章简介的存储

**Comment by xiaotiandada** [comment]
查了一下原因 建议提高Meta奖励！！！

**Comment by xiaotiandada** [comment]
#996 可测试

**Comment by guanchao71** [comment]
META奖励已发放 ：0xb8732c030748a16a7b5e5fcf1724ca28d2a174eecfc03b4520bbd4c3464db2ab
感谢您的开发
