### ISSUE TITLE
【5 META】搭建Discord社区

### ISSUE THREAD

**Issue by guanchao71** [Matataki-io/Matataki-FE#989]
瞬Matataki 原先由 Andoromeda 仙女座科技公司开发，现在正逐步向结合社区开发力量的方向演化中。
因此原有的钉钉（公司）+微信（社群）的模式就不足以支撑了，仙女座的开发者需要和社区的开发力量更加紧密的结合。因此我们选择去搭建Discord的社区，所有和Matataki相关的社群或是开发者都会逐渐向Discord频道集中。我相信这会给我们带来更好的社区开发环境和体验。

- [x] 创建服务器 ：https://discord.gg/vfB9x4GzGr
- [x] 规划分组结构
- [x] 规划权限分配
- [x] 在网站中添加Discord入口

**Comment by guanchao71** [comment]
目前已经完成服务器的创建，但是对于权限管控的设置还不太熟悉，我需要花点时间来了解。

**Comment by xiaotiandada** [comment]
#994
